# Generated by Django 4.2.30 on 2026-08-03 05:34

from attendees.persons.models import Utility
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pgtrigger.compiler
import pgtrigger.migrations
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("whereabouts", "0014_remove_addressproxy_address_snapshot_update_and_more"),
        ("pghistory", "0004_auto_20220906_1625"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persons", "0014_remove_attendee_attendee_snapshot_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PcoDivergence",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pco_person_id",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("kind", models.CharField(db_index=True, max_length=32)),
                (
                    "pointer",
                    models.CharField(
                        help_text='where the disagreement is, e.g. "$.person.first_name"',
                        max_length=120,
                    ),
                ),
                ("dedupe_key", models.CharField(db_index=True, max_length=160)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("local_value", models.JSONField(blank=True, null=True)),
                ("pco_value", models.JSONField(blank=True, null=True)),
                ("baseline_value", models.JSONField(blank=True, null=True)),
                (
                    "suggestion",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ranked match candidates, for an unmatched Planning Center person",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("warning", "warning"),
                            ("error", "error"),
                        ],
                        default="warning",
                        max_length=8,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("keep_local", "keep the attendees32 value"),
                            ("keep_pco", "keep the Planning Center value"),
                            ("ignored", "stop reporting this field for this person"),
                            ("resolved_elsewhere", "went away on its own"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("infos", models.JSONField(blank=True, default=dict)),
                (
                    "attendee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pco_divergences",
                        to="persons.attendee",
                    ),
                ),
            ],
            options={
                "db_table": "pcosync_divergences",
                "ordering": ("-severity", "kind", "pointer"),
            },
        ),
        migrations.CreateModel(
            name="PcoHouseholdLink",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pco_household_id", models.CharField(db_index=True, max_length=32)),
                (
                    "state",
                    models.CharField(
                        choices=[("live", "live"), ("gone", "gone")],
                        db_index=True,
                        default="live",
                        max_length=16,
                    ),
                ),
                (
                    "baseline",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"name": str, "members": {pco_person_id: household_role}} as of the last agreement',
                    ),
                ),
                ("baseline_synced_at", models.DateTimeField(blank=True, null=True)),
                ("infos", models.JSONField(blank=True, default=dict)),
                (
                    "folk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pco_links",
                        to="persons.folk",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=0,
                        on_delete=models.SET(0),
                        to="whereabouts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "pcosync_household_links",
                "ordering": ("organization", "pco_household_id"),
            },
        ),
        migrations.CreateModel(
            name="PcoPersonLink",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pco_person_id", models.CharField(db_index=True, max_length=32)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("live", "live"),
                            ("merged", "merged"),
                            ("gone", "gone"),
                            ("unconfirmed", "unconfirmed"),
                        ],
                        db_index=True,
                        default="live",
                        max_length=16,
                    ),
                ),
                (
                    "link_source",
                    models.CharField(
                        choices=[
                            ("uuid", "attendees_uuid custom field"),
                            ("match", "chosen by a person"),
                            ("created_here", "created in attendees32"),
                            ("created_there", "created in Planning Center"),
                        ],
                        default="uuid",
                        max_length=16,
                    ),
                ),
                (
                    "merged_into_pco_id",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "baseline",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{field_key: value} as of the last time both sides agreed. Written only on agreement or a write that succeeded.",
                    ),
                ),
                ("baseline_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "field_datum_ids",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{slug: field_datum_id}, so a PATCH knows which datum row to hit",
                    ),
                ),
                ("pco_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "infos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Example: {"ignored_fields": ["gender"]}. Please keep {} here even no data',
                    ),
                ),
                (
                    "attendee",
                    models.ForeignKey(
                        blank=True,
                        help_text="null while a Planning Center person waits to be matched",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pco_links",
                        to="persons.attendee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=0,
                        on_delete=models.SET(0),
                        to="whereabouts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "pcosync_person_links",
                "ordering": ("organization", "pco_person_id"),
            },
        ),
        migrations.CreateModel(
            name="PcoSyncRun",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("dry_run", "plan only, write nothing"),
                            (
                                "pull_only",
                                "apply to attendees32, never to Planning Center",
                            ),
                            ("full", "apply in both directions"),
                            (
                                "stamp_uuids",
                                "write attendees_uuid upstream and nothing else",
                            ),
                        ],
                        default="dry_run",
                        max_length=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("phase", models.CharField(default="definitions", max_length=24)),
                ("cursor", models.JSONField(blank=True, default=dict)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("log", models.JSONField(blank=True, default=list)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("chunks", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        default=0,
                        on_delete=models.SET(0),
                        related_name="pco_sync_runs",
                        to="whereabouts.organization",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pcosync_runs",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="PcoPersonLinksHistory",
            fields=[
                ("pgh_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("pco_person_id", models.CharField(max_length=32)),
                ("state", models.CharField(default="live", max_length=16)),
                ("link_source", models.CharField(default="uuid", max_length=16)),
                (
                    "merged_into_pco_id",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("baseline", models.JSONField(blank=True, default=dict)),
                ("baseline_synced_at", models.DateTimeField(blank=True, null=True)),
                ("field_datum_ids", models.JSONField(blank=True, default=dict)),
                ("pco_updated_at", models.DateTimeField(blank=True, null=True)),
                ("infos", models.JSONField(blank=True, default=dict)),
                (
                    "attendee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="persons.attendee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_constraint=False,
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="whereabouts.organization",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history",
                        to="pcosync.pcopersonlink",
                    ),
                ),
            ],
            options={
                "db_table": "pcosync_person_linkshistory",
            },
        ),
        migrations.CreateModel(
            name="PcoHouseholdLinksHistory",
            fields=[
                ("pgh_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("pco_household_id", models.CharField(max_length=32)),
                ("state", models.CharField(default="live", max_length=16)),
                ("baseline", models.JSONField(blank=True, default=dict)),
                ("baseline_synced_at", models.DateTimeField(blank=True, null=True)),
                ("infos", models.JSONField(blank=True, default=dict)),
                (
                    "folk",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="persons.folk",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_constraint=False,
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="whereabouts.organization",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history",
                        to="pcosync.pcohouseholdlink",
                    ),
                ),
            ],
            options={
                "db_table": "pcosync_household_linkshistory",
            },
        ),
        migrations.CreateModel(
            name="PcoDivergencesHistory",
            fields=[
                ("pgh_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("pco_person_id", models.CharField(blank=True, max_length=32)),
                ("kind", models.CharField(max_length=32)),
                ("pointer", models.CharField(max_length=120)),
                ("dedupe_key", models.CharField(max_length=160)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("local_value", models.JSONField(blank=True, null=True)),
                ("pco_value", models.JSONField(blank=True, null=True)),
                ("baseline_value", models.JSONField(blank=True, null=True)),
                ("suggestion", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                ("severity", models.CharField(default="warning", max_length=8)),
                ("resolution", models.CharField(default="open", max_length=20)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("infos", models.JSONField(blank=True, default=dict)),
                (
                    "attendee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="persons.attendee",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="pcosync.pcopersonlink",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_constraint=False,
                        default=0,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="whereabouts.organization",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history",
                        to="pcosync.pcodivergence",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="pcosync.pcosyncrun",
                    ),
                ),
            ],
            options={
                "db_table": "pcosync_divergenceshistory",
            },
        ),
        migrations.AddField(
            model_name="pcodivergence",
            name="link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="divergences",
                to="pcosync.pcopersonlink",
            ),
        ),
        migrations.AddField(
            model_name="pcodivergence",
            name="organization",
            field=models.ForeignKey(
                default=0, on_delete=models.SET(0), to="whereabouts.organization"
            ),
        ),
        migrations.AddField(
            model_name="pcodivergence",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pcodivergence",
            name="run",
            field=models.ForeignKey(
                blank=True,
                help_text="the run that last saw it, not the one that opened it",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="divergences",
                to="pcosync.pcosyncrun",
            ),
        ),
        migrations.AddIndex(
            model_name="pcosyncrun",
            index=models.Index(
                fields=["organization", "-created"], name="pcosync_run_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="pcopersonlink",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["baseline"], name="pcosync_link_baseline_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="pcopersonlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False)),
                fields=("organization", "pco_person_id"),
                name="pcosync_org_pco_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="pcopersonlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False), ("state", "live")),
                fields=("organization", "attendee"),
                name="pcosync_org_attendee_live",
            ),
        ),
        migrations.AddConstraint(
            model_name="pcohouseholdlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False)),
                fields=("organization", "pco_household_id"),
                name="pcosync_org_pco_household",
            ),
        ),
        migrations.AddIndex(
            model_name="pcodivergence",
            index=models.Index(
                fields=["organization", "resolution", "kind"], name="pcosync_div_triage"
            ),
        ),
        migrations.AddConstraint(
            model_name="pcodivergence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False), ("resolution", "open")),
                fields=("organization", "dedupe_key"),
                name="pcosync_one_open_divergence",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pcopersonlink",
            trigger=pgtrigger.compiler.Trigger(
                name="pcopersonlink_snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pcosync_person_linkshistory" ("id", "created", "modified", "is_removed", "organization_id", "attendee_id", "pco_person_id", "state", "link_source", "merged_into_pco_id", "baseline", "baseline_synced_at", "field_datum_ids", "pco_updated_at", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."organization_id", NEW."attendee_id", NEW."pco_person_id", NEW."state", NEW."link_source", NEW."merged_into_pco_id", NEW."baseline", NEW."baseline_synced_at", NEW."field_datum_ids", NEW."pco_updated_at", NEW."infos", NOW(), \'pcopersonlink.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;',
                    hash="ffdb28723fb632051a9afcb9c02895d41ea4507a",
                    operation="INSERT",
                    pgid="pgtrigger_pcopersonlink_snapshot_insert_96aa4",
                    table="pcosync_person_links",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pcopersonlink",
            trigger=pgtrigger.compiler.Trigger(
                name="pcopersonlink_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."attendee_id" IS DISTINCT FROM (NEW."attendee_id") OR OLD."pco_person_id" IS DISTINCT FROM (NEW."pco_person_id") OR OLD."state" IS DISTINCT FROM (NEW."state") OR OLD."link_source" IS DISTINCT FROM (NEW."link_source") OR OLD."merged_into_pco_id" IS DISTINCT FROM (NEW."merged_into_pco_id") OR OLD."baseline" IS DISTINCT FROM (NEW."baseline") OR OLD."baseline_synced_at" IS DISTINCT FROM (NEW."baseline_synced_at") OR OLD."field_datum_ids" IS DISTINCT FROM (NEW."field_datum_ids") OR OLD."pco_updated_at" IS DISTINCT FROM (NEW."pco_updated_at") OR OLD."infos" IS DISTINCT FROM (NEW."infos"))',
                    func='INSERT INTO "pcosync_person_linkshistory" ("id", "created", "modified", "is_removed", "organization_id", "attendee_id", "pco_person_id", "state", "link_source", "merged_into_pco_id", "baseline", "baseline_synced_at", "field_datum_ids", "pco_updated_at", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."organization_id", NEW."attendee_id", NEW."pco_person_id", NEW."state", NEW."link_source", NEW."merged_into_pco_id", NEW."baseline", NEW."baseline_synced_at", NEW."field_datum_ids", NEW."pco_updated_at", NEW."infos", NOW(), \'pcopersonlink.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;',
                    hash="a66ffb804af65804280fcc9803d6ee3e195fc845",
                    operation="UPDATE",
                    pgid="pgtrigger_pcopersonlink_snapshot_update_a7dd7",
                    table="pcosync_person_links",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pcopersonlink",
            trigger=pgtrigger.compiler.Trigger(
                name="pcopersonlink_before_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pcosync_person_linkshistory" ("id", "created", "modified", "is_removed", "organization_id", "attendee_id", "pco_person_id", "state", "link_source", "merged_into_pco_id", "baseline", "baseline_synced_at", "field_datum_ids", "pco_updated_at", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."id", OLD."created", OLD."modified", OLD."is_removed", OLD."organization_id", OLD."attendee_id", OLD."pco_person_id", OLD."state", OLD."link_source", OLD."merged_into_pco_id", OLD."baseline", OLD."baseline_synced_at", OLD."field_datum_ids", OLD."pco_updated_at", OLD."infos", NOW(), \'pcopersonlink.before_delete\', OLD."id", _pgh_attach_context()); RETURN NULL;',
                    hash="97d2e6e371432837af70dd121971309c24cfb82b",
                    operation="DELETE",
                    pgid="pgtrigger_pcopersonlink_before_delete_5c07f",
                    table="pcosync_person_links",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pcohouseholdlink",
            trigger=pgtrigger.compiler.Trigger(
                name="pcohouseholdlink_snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pcosync_household_linkshistory" ("id", "created", "modified", "is_removed", "organization_id", "folk_id", "pco_household_id", "state", "baseline", "baseline_synced_at", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."organization_id", NEW."folk_id", NEW."pco_household_id", NEW."state", NEW."baseline", NEW."baseline_synced_at", NEW."infos", NOW(), \'pcohouseholdlink.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;',
                    hash="3f747fa48f36f1267727c9aeafd9b6f82dd0db86",
                    operation="INSERT",
                    pgid="pgtrigger_pcohouseholdlink_snapshot_insert_fe0db",
                    table="pcosync_household_links",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pcohouseholdlink",
            trigger=pgtrigger.compiler.Trigger(
                name="pcohouseholdlink_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."folk_id" IS DISTINCT FROM (NEW."folk_id") OR OLD."pco_household_id" IS DISTINCT FROM (NEW."pco_household_id") OR OLD."state" IS DISTINCT FROM (NEW."state") OR OLD."baseline" IS DISTINCT FROM (NEW."baseline") OR OLD."baseline_synced_at" IS DISTINCT FROM (NEW."baseline_synced_at") OR OLD."infos" IS DISTINCT FROM (NEW."infos"))',
                    func='INSERT INTO "pcosync_household_linkshistory" ("id", "created", "modified", "is_removed", "organization_id", "folk_id", "pco_household_id", "state", "baseline", "baseline_synced_at", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."organization_id", NEW."folk_id", NEW."pco_household_id", NEW."state", NEW."baseline", NEW."baseline_synced_at", NEW."infos", NOW(), \'pcohouseholdlink.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;',
                    hash="a522a93fd0415c50c94ad5d2c5321f035df600e9",
                    operation="UPDATE",
                    pgid="pgtrigger_pcohouseholdlink_snapshot_update_a8cf4",
                    table="pcosync_household_links",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pcohouseholdlink",
            trigger=pgtrigger.compiler.Trigger(
                name="pcohouseholdlink_before_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pcosync_household_linkshistory" ("id", "created", "modified", "is_removed", "organization_id", "folk_id", "pco_household_id", "state", "baseline", "baseline_synced_at", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."id", OLD."created", OLD."modified", OLD."is_removed", OLD."organization_id", OLD."folk_id", OLD."pco_household_id", OLD."state", OLD."baseline", OLD."baseline_synced_at", OLD."infos", NOW(), \'pcohouseholdlink.before_delete\', OLD."id", _pgh_attach_context()); RETURN NULL;',
                    hash="701fd21057b2442ae1c4506d8ceec47af2593bb9",
                    operation="DELETE",
                    pgid="pgtrigger_pcohouseholdlink_before_delete_c8acd",
                    table="pcosync_household_links",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pcodivergence",
            trigger=pgtrigger.compiler.Trigger(
                name="pcodivergence_snapshot_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pcosync_divergenceshistory" ("id", "created", "modified", "is_removed", "organization_id", "run_id", "link_id", "attendee_id", "resolved_by_id", "pco_person_id", "kind", "pointer", "dedupe_key", "label", "local_value", "pco_value", "baseline_value", "suggestion", "note", "severity", "resolution", "resolved_at", "first_seen_at", "last_seen_at", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."organization_id", NEW."run_id", NEW."link_id", NEW."attendee_id", NEW."resolved_by_id", NEW."pco_person_id", NEW."kind", NEW."pointer", NEW."dedupe_key", NEW."label", NEW."local_value", NEW."pco_value", NEW."baseline_value", NEW."suggestion", NEW."note", NEW."severity", NEW."resolution", NEW."resolved_at", NEW."first_seen_at", NEW."last_seen_at", NEW."infos", NOW(), \'pcodivergence.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;',
                    hash="4a18782daac36f9d5430f737c61366cb9a2fe9c3",
                    operation="INSERT",
                    pgid="pgtrigger_pcodivergence_snapshot_insert_f91de",
                    table="pcosync_divergences",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pcodivergence",
            trigger=pgtrigger.compiler.Trigger(
                name="pcodivergence_snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."is_removed" IS DISTINCT FROM (NEW."is_removed") OR OLD."organization_id" IS DISTINCT FROM (NEW."organization_id") OR OLD."run_id" IS DISTINCT FROM (NEW."run_id") OR OLD."link_id" IS DISTINCT FROM (NEW."link_id") OR OLD."attendee_id" IS DISTINCT FROM (NEW."attendee_id") OR OLD."resolved_by_id" IS DISTINCT FROM (NEW."resolved_by_id") OR OLD."pco_person_id" IS DISTINCT FROM (NEW."pco_person_id") OR OLD."kind" IS DISTINCT FROM (NEW."kind") OR OLD."pointer" IS DISTINCT FROM (NEW."pointer") OR OLD."dedupe_key" IS DISTINCT FROM (NEW."dedupe_key") OR OLD."label" IS DISTINCT FROM (NEW."label") OR OLD."local_value" IS DISTINCT FROM (NEW."local_value") OR OLD."pco_value" IS DISTINCT FROM (NEW."pco_value") OR OLD."baseline_value" IS DISTINCT FROM (NEW."baseline_value") OR OLD."suggestion" IS DISTINCT FROM (NEW."suggestion") OR OLD."note" IS DISTINCT FROM (NEW."note") OR OLD."severity" IS DISTINCT FROM (NEW."severity") OR OLD."resolution" IS DISTINCT FROM (NEW."resolution") OR OLD."resolved_at" IS DISTINCT FROM (NEW."resolved_at") OR OLD."first_seen_at" IS DISTINCT FROM (NEW."first_seen_at") OR OLD."last_seen_at" IS DISTINCT FROM (NEW."last_seen_at") OR OLD."infos" IS DISTINCT FROM (NEW."infos"))',
                    func='INSERT INTO "pcosync_divergenceshistory" ("id", "created", "modified", "is_removed", "organization_id", "run_id", "link_id", "attendee_id", "resolved_by_id", "pco_person_id", "kind", "pointer", "dedupe_key", "label", "local_value", "pco_value", "baseline_value", "suggestion", "note", "severity", "resolution", "resolved_at", "first_seen_at", "last_seen_at", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (NEW."id", NEW."created", NEW."modified", NEW."is_removed", NEW."organization_id", NEW."run_id", NEW."link_id", NEW."attendee_id", NEW."resolved_by_id", NEW."pco_person_id", NEW."kind", NEW."pointer", NEW."dedupe_key", NEW."label", NEW."local_value", NEW."pco_value", NEW."baseline_value", NEW."suggestion", NEW."note", NEW."severity", NEW."resolution", NEW."resolved_at", NEW."first_seen_at", NEW."last_seen_at", NEW."infos", NOW(), \'pcodivergence.snapshot\', NEW."id", _pgh_attach_context()); RETURN NULL;',
                    hash="e06e45dcbfd065dd48ec28741545cad2577142cc",
                    operation="UPDATE",
                    pgid="pgtrigger_pcodivergence_snapshot_update_b133a",
                    table="pcosync_divergences",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="pcodivergence",
            trigger=pgtrigger.compiler.Trigger(
                name="pcodivergence_before_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pcosync_divergenceshistory" ("id", "created", "modified", "is_removed", "organization_id", "run_id", "link_id", "attendee_id", "resolved_by_id", "pco_person_id", "kind", "pointer", "dedupe_key", "label", "local_value", "pco_value", "baseline_value", "suggestion", "note", "severity", "resolution", "resolved_at", "first_seen_at", "last_seen_at", "infos", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."id", OLD."created", OLD."modified", OLD."is_removed", OLD."organization_id", OLD."run_id", OLD."link_id", OLD."attendee_id", OLD."resolved_by_id", OLD."pco_person_id", OLD."kind", OLD."pointer", OLD."dedupe_key", OLD."label", OLD."local_value", OLD."pco_value", OLD."baseline_value", OLD."suggestion", OLD."note", OLD."severity", OLD."resolution", OLD."resolved_at", OLD."first_seen_at", OLD."last_seen_at", OLD."infos", NOW(), \'pcodivergence.before_delete\', OLD."id", _pgh_attach_context()); RETURN NULL;',
                    hash="6ee6f269eeb7bdac6f10ac55bc7a24286a705fbe",
                    operation="DELETE",
                    pgid="pgtrigger_pcodivergence_before_delete_97c9c",
                    table="pcosync_divergences",
                    when="AFTER",
                ),
            ),
        ),
        migrations.RunSQL(Utility.default_sql("pcosync_person_links")),
        migrations.RunSQL(Utility.default_sql("pcosync_household_links")),
        migrations.RunSQL(Utility.default_sql("pcosync_divergences")),
        migrations.RunSQL(Utility.pgh_default_sql(
            "pcosync_person_linkshistory",
            table_comment="the attendees32 <-> Planning Center person join, and its baseline",
            original_model_table="pcosync_person_links",
        )),
        migrations.RunSQL(Utility.pgh_default_sql(
            "pcosync_household_linkshistory",
            table_comment="the Folk <-> Planning Center household join",
            original_model_table="pcosync_household_links",
        )),
        migrations.RunSQL(Utility.pgh_default_sql(
            "pcosync_divergenceshistory",
            table_comment="disagreements between attendees32 and Planning Center",
            original_model_table="pcosync_divergences",
        )),
    ]
